### ISSUE TITLE
 SNMP: Scalars do not have a .0 suffix

### ISSUE THREAD

**Issue by shmuelhazan** [clicon/clixon#401] opened 2023-01-16 09:16 UTC
When we tried to integrate standard yang models like IF-MIB and standard SNMP tools, we noticed that they are trying to access scalars without a table with the .0 suffix (for example, `1.3.6.1.2.1.2.1` from https://github.com/clicon/mib-yangs/blob/main/IF-MIB.yang#L129 will be accessed as `1.3.6.1.2.1.2.1.0`). 

Since clixon register them without the trailing .0, they will get error in result. 

After doing some research, looks like we indeed need to add .0 to scalars:
> A scalar variable has a single instance and is identified by its ".0". On the other hand, a table object or the columnar variable can have one or more instances and is identified by its index value. To identify a specific columnar variable, the index of the row has to be appended to its OID.
(https://www.webnms.com/snmp/help/snmpapi/snmpv3/table_handling/snmptables_basics.html)

Also from the RFC (https://www.rfc-editor.org/rfc/rfc1157#section-3.2.6.3):
> Instances of an object type to which none of the following naming conventions are applicable are named by OBJECT IDENTIFIERs of the form x.0, where x is the name of said object type in the MIB definition.

**Comment by olofhagsand** [comment] 2023-02-06 11:54
Merged into master. Please verify.

**Comment by dima1308** [comment] 2023-02-15 17:41
we verified that the issue is solved.
```
Protocol version: SNMPv2c
Operation: Get
Request binding:
1: ifNumber.0 (Integer32) null

Response binding:
1: ifNumber.0 (Integer32) 4
```

**Closed** 2023-02-15 20:38 UTC
Labels: bug, fixed please verify
