### ISSUE TITLE
Multiple ranges support

### ISSUE THREAD

**Issue by achernavin22** [clicon/clixon#78] opened 2019-02-28 13:53 UTC
Given the filed:
```
leaf field_name {
    type uint8 {
        range "4..16 | 32..64";
    }
}
```

Now, validation takes into account only the first range.

**Comment by olofhagsand** [comment] 2019-02-28 21:19
To be precise, this is a bug in the CLI only, multiple ranges works with restconf and netconf as can be seen in  this example (where the value is set w netconf and validated in the CLI):
```
olof@vandal> clixon_netconf -qf /usr/local/etc/example.xml 
<rpc><edit-config><target><candidate/></target><config><field_name xmlns="urn:example:clixon">33</field_name></config></edit-config></rpc>]]>]]>
<rpc-reply><ok/></rpc-reply>]]>]]>^C
olof@vandal> clixon_cli -f /usr/local/etc/example.xml  
olof@vandal> show configuration 
field_name 33;
olof@vandal> validate 
olof@vandal> 
```
It is therefore a duplicate of [https://github.com/clicon/clixon/issues/59]
Please tell if there is some other use-case where it does not work.

**Comment by achernavin22** [comment] 2019-03-01 08:37
Sorry, I tested it via RESTCONF. Having that filed and passing 50 as a value results in error:
```
{
    "ietf-restconf:errors": {
        "error": {
            "error-type": "application",
            "error-tag": "bad-element",
            "error-info": {
                "bad-element": "field_name"
            },
            "error-severity": "error",
            "error-message": "Number out of range: 50"
        }
    }
}
```

Probably that is because of the older version (from Jan 18, 2019).

**Comment by olofhagsand** [comment] 2019-03-01 11:11
Can you please verify it works on later version, I may have missed a use-case? Or wait a day or two since I am trying to fix the remaining CLI problem now.

**Comment by olofhagsand** [comment] 2019-03-04 13:38
Should be fixed now. Including CLI.

**Closed** 2019-03-04 13:40 UTC
Labels: duplicate
