### ISSUE TITLE
error message on hello reply

### ISSUE THREAD

**Issue by dima1308** [clicon/clixon#187] opened 2021-03-08 12:11 UTC
Hi @olofhagsand 
Please see:
```
dimag@dali:~$ ssh admin@172.20.20.101 -s netconf
admin@172.20.20.101's password:
<hello xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="42"><capabilities><capability>urn:ietf:params:netconf:base:1.0</capability><capability>urn:ietf:params:netconf:capability:candidate:1.0</capability><capability>urn:ietf:params:netconf:capability:validate:1.1</capability><capability>urn:ietf:params:netconf:capability:startup:1.0</capability><capability>urn:ietf:params:netconf:capability:xpath:1.0</capability><capability>urn:ietf:params:netconf:capability:notification:1.0</capability></capabilities><session-id>8</session-id></hello>]]>]]>
<?xml version="1.0" encoding="UTF-8"?>
<nc:hello xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0">
  <nc:capabilities>
    <nc:capability>urn:ietf:params:netconf:base:1.0</nc:capability>
    <nc:capability>urn:ietf:params:netconf:base:1.1</nc:capability>
    <nc:capability>urn:ietf:params:netconf:capability:writable-running:1.0</nc:capability>
    <nc:capability>urn:ietf:params:netconf:capability:candidate:1.0</nc:capability>
    <nc:capability>urn:ietf:params:netconf:capability:confirmed-commit:1.0</nc:capability>
    <nc:capability>urn:ietf:params:netconf:capability:rollback-on-error:1.0</nc:capability>
    <nc:capability>urn:ietf:params:netconf:capability:startup:1.0</nc:capability>
    <nc:capability>urn:ietf:params:netconf:capability:url:1.0?scheme=http,ftp,file,https,sftp</nc:capability>
    <nc:capability>urn:ietf:params:netconf:capability:validate:1.0</nc:capability>
    <nc:capability>urn:ietf:params:netconf:capability:xpath:1.0</nc:capability>
    <nc:capability>urn:ietf:params:netconf:capability:notification:1.0</nc:capability>
    <nc:capability>urn:liberouter:params:netconf:capability:power-control:1.0</nc:capability>
    <nc:capability>urn:ietf:params:netconf:capability:interleave:1.0</nc:capability>
    <nc:capability>urn:ietf:params:netconf:capability:with-defaults:1.0</nc:capability>
  </nc:capabilities>
</nc:hello>]]>]]>
<rpc-reply xmlns="urn:ietf:params:xml:ns:netconf:base:1.0"><rpc-error><error-type>rpc</error-type><error-tag>operation-failed</error-tag><error-severity>error</error-severity><error-message>xml_parse: line 0: syntax error: at or before: &lt;/</error-message></rpc-error></rpc-reply>]]>]]>
```
The `hello` message we sent is generated by the ncclient python library and we got the error listed above.
Can you please take a look?

**Comment by olofhagsand** [comment] 2021-03-08 12:59
I cant replicate this issue.
I assume the first hello is from clixon and the second hello from the client, and that the rpc-reply is from clixon.
But is there not an RPC from the client as well? If you use message-id one should see which rpc the reply is associated with.

**Comment by dima1308** [comment] 2021-03-08 13:04
yes, the first message is from the CLIXON:
```
dimag@dali:~$ ssh admin@172.20.20.101 -s netconf
admin@172.20.20.101's password:
<hello xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="42"><capabilities><capability>urn:ietf:params:netconf:base:1.0</capability><capability>urn:ietf:params:netconf:capability:candidate:1.0</capability><capability>urn:ietf:params:netconf:capability:validate:1.1</capability><capability>urn:ietf:params:netconf:capability:startup:1.0</capability><capability>urn:ietf:params:netconf:capability:xpath:1.0</capability><capability>urn:ietf:params:netconf:capability:notification:1.0</capability></capabilities><session-id>12</session-id></hello>]]>]]>
```
To reproduce the issue, I connect to the device using the following command:
'ssh admin@172.20.20.101 -s netconf '
and after it, send this message:
```
<?xml version="1.0" encoding="UTF-8"?>
<nc:hello xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0">
  <nc:capabilities>
    <nc:capability>urn:ietf:params:netconf:base:1.0</nc:capability>
    <nc:capability>urn:ietf:params:netconf:base:1.1</nc:capability>
    <nc:capability>urn:ietf:params:netconf:capability:writable-running:1.0</nc:capability>
    <nc:capability>urn:ietf:params:netconf:capability:candidate:1.0</nc:capability>
    <nc:capability>urn:ietf:params:netconf:capability:confirmed-commit:1.0</nc:capability>
    <nc:capability>urn:ietf:params:netconf:capability:rollback-on-error:1.0</nc:capability>
    <nc:capability>urn:ietf:params:netconf:capability:startup:1.0</nc:capability>
    <nc:capability>urn:ietf:params:netconf:capability:url:1.0?scheme=http,ftp,file,https,sftp</nc:capability>
    <nc:capability>urn:ietf:params:netconf:capability:validate:1.0</nc:capability>
    <nc:capability>urn:ietf:params:netconf:capability:xpath:1.0</nc:capability>
    <nc:capability>urn:ietf:params:netconf:capability:notification:1.0</nc:capability>
    <nc:capability>urn:liberouter:params:netconf:capability:power-control:1.0</nc:capability>
    <nc:capability>urn:ietf:params:netconf:capability:interleave:1.0</nc:capability>
    <nc:capability>urn:ietf:params:netconf:capability:with-defaults:1.0</nc:capability>
  </nc:capabilities>
</nc:hello>]]>]]>
```

**Comment by olofhagsand** [comment] 2021-03-08 13:10
I still cannot reproduce.
- Are you using master? If not, which version?
- Can you recreate it by piping the output above directly to `clixon_netconf`?

**Comment by olofhagsand** [comment] 2021-03-09 08:58
Please check this commit, where these issues are addressed:
https://github.com/clicon/clixon/commit/8cde7a4deda943d39196c64ffbd15d4441cbf7c9

**Comment by olofhagsand** [comment] 2021-03-22 09:31
Closing this since the report was made on an earlier version which has been addressed after that.
Please reopen if still remains.

**Closed by olofhagsand** 2021-03-22 09:31 UTC
Labels: bug
