### ISSUE TITLE
XPATH issues

### ISSUE THREAD

**Issue by dima1308** [clicon/clixon#219] opened 2021-05-10 11:56 UTC
we implemented an inventory display. To read inventory display parameters we use the following query:
```
<get>
  <filter type="subtree">
    <rb-tg-inv:inventory xmlns:rb-tg-inv="http://siklu.com/yang/tg/inventory"/>
  </filter>
</get>
```
The output is:
```
<?xml version="1.0" encoding="utf-8"?>
<data xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
  <inventory xmlns="http://siklu.com/yang/tg/inventory">
    <component>
      <name>Baseband</name>
      <parent>MH-T265</parent>
      <parent-rel-pos>0</parent-rel-pos>
      <child>
        <name>Bootloader</name>
      </child>
      <child>
        <name>eth1</name>
      </child>
      <child>
        <name>eth2</name>
      </child>
      <child>
        <name>eth3</name>
      </child>
      <hardware-rev>A1.0</hardware-rev>
      <serial-num>F047419434</serial-num>
      <is-fru>false</is-fru>
    </component>
    <component>
      <name>Bootloader</name>
      <parent>Baseband</parent>
      <parent-rel-pos>0</parent-rel-pos>
      <firmware-rev>unavailable</firmware-rev>
      <is-fru>false</is-fru>
    </component>
    <component>
      <name>MH-T265</name>
      <description>MH-T265</description>
      <child>
        <name>Baseband</name>
      </child>
      <child>
        <name>RF sector 1</name>
      </child>
      <hardware-rev>0</hardware-rev>
      <software-rev>1.0.3-1867-5f8ea891-debug</software-rev>
      <serial-num>F047419434</serial-num>
      <mfg-name>Siklu</mfg-name>
      <model-name>MH-T265-CCP-PoE-MWB-SPIDER</model-name>
      <is-fru>true</is-fru>
    </component>
    <component>
      <name>RF sector 1</name>
      <parent>MH-T265</parent>
      <parent-rel-pos>1</parent-rel-pos>
      <child>
        <name>RF sector 1 Antenna</name>
      </child>
      <is-fru>false</is-fru>
    </component>
    <component>
      <name>RF sector 1 Antenna</name>
      <description>Conducted Spider</description>
      <parent>RF sector 1</parent>
      <parent-rel-pos>0</parent-rel-pos>
      <is-fru>false</is-fru>
    </component>
    <component>
      <name>eth1</name>
      <description>RJ-45,10G/5G/2.5G/1G/100M</description>
      <parent>Baseband</parent>
      <parent-rel-pos>3</parent-rel-pos>
      <is-fru>false</is-fru>
    </component>
    <component>
      <name>eth2</name>
      <description>RJ-45,1G/100M</description>
      <parent>Baseband</parent>
      <parent-rel-pos>1</parent-rel-pos>
      <child>
        <name>eth2_pse</name>
      </child>
      <is-fru>false</is-fru>
    </component>
    <component>
      <name>eth2_pse</name>
      <parent>eth2</parent>
      <parent-rel-pos>0</parent-rel-pos>
      <is-fru>false</is-fru>
    </component>
    <component>
      <name>eth3</name>
      <description>SFP+,10G/1G cage</description>
      <parent>Baseband</parent>
      <parent-rel-pos>2</parent-rel-pos>
      <is-fru>false</is-fru>
    </component>
  </inventory>
</data>
```
Now, I'm trying to run different XPATH queries on it.
example 1:
```
<get>
     <filter xmlns: rb-tg-inv='http://siklu.com/yang/tg/inventory'
             type="xpath"
             select="/rb-tg-inv:inventory/rb-tg-inv:component[@rb-tg-inv:name='MH-T265' | @rb-tg-inv:name='MH-T266']"/>
</get>
```
The result is:
```
<?xml version="1.0" encoding="utf-8"?>
<rpc-reply xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="117">
  <rpc-error>
    <error-type>application</error-type>
    <error-tag>operation-failed</error-tag>
    <error-severity>error</error-severity>
    <error-message>read registry</error-message>
  </rpc-error>
</rpc-reply>
```
In this case, I expect to get something like:
```
<?xml version="1.0" encoding="utf-8"?>
<data xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
  <inventory xmlns="http://siklu.com/yang/tg/inventory">
    <component>
      <name>MH-T265</name>
      <description>MH-T265</description>
      <child>
        <name>Baseband</name>
      </child>
      <child>
        <name>RF sector 1</name>
      </child>
      <hardware-rev>0</hardware-rev>
      <software-rev>1.0.3-1867-5f8ea891-debug</software-rev>
      <serial-num>F047419434</serial-num>
      <mfg-name>Siklu</mfg-name>
      <model-name>MH-T265-CCP-PoE-MWB-SPIDER</model-name>
      <is-fru>true</is-fru>
    </component>
  </inventory>
</data>
```
Note: if I use `or` instead of `|`, the problem is the same

example 2:
```
<get>
     <filter xmlns: rb-tg-inv='http://siklu.com/yang/tg/inventory'
             type="xpath"
             select="/rb-tg-inv:inventory/rb-tg-inv:component[not(@rb-tg-inv:parent)]"/>
</get>
```
In this case, I expect to get all entries where the `parent` attribute does not exist (in my case, we have only one top-level entry with no parent):
```
<?xml version="1.0" encoding="utf-8"?>
<data xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
  <inventory xmlns="http://siklu.com/yang/tg/inventory">
    <component>
      <name>MH-T265</name>
      <description>MH-T265</description>
      <child>
        <name>Baseband</name>
      </child>
      <child>
        <name>RF sector 1</name>
      </child>
      <hardware-rev>0</hardware-rev>
      <software-rev>1.0.3-1867-5f8ea891-debug</software-rev>
      <serial-num>F047419434</serial-num>
      <mfg-name>Siklu</mfg-name>
      <model-name>MH-T265-CCP-PoE-MWB-SPIDER</model-name>
      <is-fru>true</is-fru>
    </component>
  </inventory>
</data>
```
But actually, I got the following output:
```
<?xml version="1.0" encoding="utf-8"?>
<data xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
  <inventory xmlns="http://siklu.com/yang/tg/inventory">
    <component>
      <name>Baseband</name>
      <parent>MH-T265</parent>
      <parent-rel-pos>0</parent-rel-pos>
      <child>
        <name>Bootloader</name>
      </child>
      <child>
        <name>eth1</name>
      </child>
      <child>
        <name>eth2</name>
      </child>
      <child>
        <name>eth3</name>
      </child>
      <hardware-rev>A1.0</hardware-rev>
      <serial-num>F047419434</serial-num>
      <is-fru>false</is-fru>
    </component>
    <component>
      <name>Bootloader</name>
      <parent>Baseband</parent>
      <parent-rel-pos>0</parent-rel-pos>
      <firmware-rev>unavailable</firmware-rev>
      <is-fru>false</is-fru>
    </component>
    <component>
      <name>RF sector 1</name>
      <parent>MH-T265</parent>
      <parent-rel-pos>1</parent-rel-pos>
      <child>
        <name>RF sector 1 Antenna</name>
      </child>
      <is-fru>false</is-fru>
    </component>
    <component>
      <name>RF sector 1 Antenna</name>
      <description>Conducted Spider</description>
      <parent>RF sector 1</parent>
      <parent-rel-pos>0</parent-rel-pos>
      <is-fru>false</is-fru>
    </component>
    <component>
      <name>eth1</name>
      <description>RJ-45,10G/5G/2.5G/1G/100M</description>
      <parent>Baseband</parent>
      <parent-rel-pos>3</parent-rel-pos>
      <is-fru>false</is-fru>
    </component>
    <component>
      <name>eth2</name>
      <description>RJ-45,1G/100M</description>
      <parent>Baseband</parent>
      <parent-rel-pos>1</parent-rel-pos>
      <child>
        <name>eth2_pse</name>
      </child>
      <is-fru>false</is-fru>
    </component>
    <component>
      <name>eth2_pse</name>
      <parent>eth2</parent>
      <parent-rel-pos>0</parent-rel-pos>
      <is-fru>false</is-fru>
    </component>
    <component>
      <name>eth3</name>
      <description>SFP+,10G/1G cage</description>
      <parent>Baseband</parent>
      <parent-rel-pos>2</parent-rel-pos>
      <is-fru>false</is-fru>
    </component>
  </inventory>
</data>
```
example 3:
```
<get>
     <filter xmlns: rb-tg-inv='http://siklu.com/yang/tg/inventory'
             type="xpath"
             select="/rb-tg-inv:inventory/rb-tg-inv:component[starts-with(@rb-tg-inv:name, 'MH-')]"/>
</get>
```
The output is:
```
<?xml version="1.0" encoding="utf-8"?>
<rpc-reply xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="123">
  <rpc-error>
    <error-type>application</error-type>
    <error-tag>operation-failed</error-tag>
    <error-severity>error</error-severity>
    <error-message>xpath parser on line 1: XPATH function "starts-with" is not implemented at or before: ')'</error-message>
  </rpc-error>
</rpc-reply>
```
example 4:
```
<get>
     <filter xmlns: rb-tg-inv='http://siklu.com/yang/tg/inventory'
             type="xpath"
             select="/rb-tg-inv:inventory/rb-tg-inv:component[contains(@rb-tg-inv:name,'MH-')]"/>
</get>
```
The output is:
```
<?xml version="1.0" encoding="utf-8"?>
<rpc-reply xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="125">
  <rpc-error>
    <error-type>application</error-type>
    <error-tag>operation-failed</error-tag>
    <error-severity>error</error-severity>
    <error-message>read registry</error-message>
  </rpc-error>
</rpc-reply>
```

**Comment by olofhagsand** [comment] 2021-05-14 11:31
One error in your xpath statement is your use of "@". According to https://www.w3.org/TR/xpath-10/ "@" means attribute, but your use here is name of child node.
For example, try: 
```
rb-tg-inv:component[@rb-tg-inv:name='MH-T265' --> rb-tg-inv:component[rb-tg-inv:name='MH-T265'
```

**Comment by dima1308** [comment] 2021-05-14 11:51
@olofhagsand I tried to remove @ as you suggested, but the issue is still.
For example, if I do command like:
```
<get>
     <filter xmlns: rb-tg-inv='http://siklu.com/yang/tg/inventory'
             type="xpath"
             select="/rb-tg-inv:inventory/rb-tg-inv:component[rb-tg-inv:name='MH-N366' | rb-tg-inv:name='MH-N367']"/>
</get>
```
I'm getting the response:
```
<?xml version="1.0" encoding="utf-8"?>
<rpc-reply xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="12">
  <rpc-error>
    <error-type>application</error-type>
    <error-tag>operation-failed</error-tag>
    <error-severity>error</error-severity>
    <error-message>read registry</error-message>
  </rpc-error>
</rpc-reply>
```
If I remove "|", the following command is working as expected:
```
<get>
     <filter xmlns: rb-tg-inv='http://siklu.com/yang/tg/inventory'
             type="xpath"
             select="/rb-tg-inv:inventory/rb-tg-inv:component[rb-tg-inv:name='MH-N366']"/>
</get>
```

Also, what about all the other examples I set you?

**Comment by olofhagsand** [comment] 2021-05-14 19:54
The `not` operation does not look well-formed. Try eg: 
`[componentnot(rb-tg-inv:parent='MH-T265')]`
For all components that does not have field parent equal to MH-T265

**Comment by olofhagsand** [comment] 2021-05-15 20:09
Thanks for looking into this. There is lots of stuff here. You look into four cases:
1. Union
   First, a union '|' is only defined on nodesets, see https://www.w3.org/TR/xpath-10/#node-sets :
   > The | operator computes the union of its operands, which must be node-sets.
   
But the usage in your example is on booleans: `[name='MH-T265' | name='MH-T266']` but there is also operator precedence here, so to be clear it should be written:  `[(name='MH-T265') | (name='MH-T266')] ` but still operates on boolean ('=' returns boolean)
   Again, since it is defined on nodesets, maybe how you should write it is somethng like: 
 `  inventory/component[rb-tg-inv:name='MH-N366' ] | inventory/component[rb-tg-inv:name='MH-N367']`
 That said, there was an error in the union handling in clixon - I will add a patch.
 2. not(parent) - I can recreate that, I got your expected outcome using:
```
     if (xpath_vec(xt, nsc, "data/inventory/component[not(parent)]", &vec, &veclen) < 0) 
	goto done;
```
3. starts-with. Not implemented, see https://clixon-docs.readthedocs.io/en/latest/standards.html#xml-and-xpath
It is relatively straigh-forward to implement if needed.

4. contains: Cannot recreate with this: statement:
```
         if (xpath_vec(xt, nsc, "data/inventory/component[contains(name,'MH-')]", &vec, &veclen) < 0) 
<component>
   <name>MH-N367</name>
   <description>MH-T265</description>
   <child>
      <name>Baseband</name>
   </child>
   <child>
      <name>RF sector 1</name>
   </child>
   <hardware-rev>0</hardware-rev>
   <software-rev>1.0.3-1867-5f8ea891-debug</software-rev>
   <serial-num>F047419434</serial-num>
   <mfg-name>Siklu</mfg-name>
   <model-name>MH-T265-CCP-PoE-MWB-SPIDER</model-name>
   <is-fru>true</is-fru>
```

**Comment by dima1308** [comment] 2021-05-15 21:58
@olofhagsand thank you for your answer and for the patch.

for issue 2 - not(parent) - how should I run the query using netconf xpath? As I understand, I run the same xpath as you run. Maybe I did something wrong.
for issue 4 - probably you are using the wrong input, in my example `<name>MH-N367</name>` does not exist. May I ask you to send me the input XML you are using? Probably the input XML is not the same as I'm using.

**Comment by olofhagsand** [comment] 2021-05-16 20:49
Yes I can confirm problems with XPATH composite operations and functions in netconf get operations.
It works in regression tests since they are unit and not end-to-end netconf tests.
This is a bug and will be fixed.

**Comment by olofhagsand** [comment] 2021-05-17 08:53
2 and 4 should be fixed by patch.
Please verify

**Comment by dima1308** [comment] 2021-05-20 12:56
thanks, @olofhagsand will verity.

**Closed** 2021-05-24 12:55 UTC
Labels: bug
